server:
  servlet:
    context-path: /gerencia-funcionario/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://${MONGO_DB_USER}:${MONGO_DB_PASS}@cluster0.peh5zhp.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0}
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /public/swagger


gerencia-funcionario:
  security:
    token:
      api: ${apiName:"gerencia-funcionario"}
      secret: ${SECRET:"semente_secret"}

